# Numpy: Part 4

In this notebook, you will learn:
 - Broadcasting
 
Read more: 
 - textbook https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) and
 - [Numpy website] (https://numpy.org/).

In [2]:
import numpy as np

### 1. Broadcasting

Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy broadcasting.

**Loop based approach** without broadcasting

In [4]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x
print(x,"\n\n", v,"\n")

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print (y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [1 0 1] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Alterenatively, you can make **v** to be compatible with **x**

In [103]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other (4 rows of v, so (4, 1))
print (vv,"\n")          # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"
            
y = x + vv  # Add x and vv elementwise
print (y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**Numpy broadcasting** allows us to perform this computation without actually creating multiple copies of v.

In [20]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(x,"\n\n", v)
print("\n Shapes\n", x.shape, '\n   ', v.shape, '\n ------\n', x.shape, '\n')
print (y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [1 0 1]

 Shapes
 (4, 3) 
    (3,) 
 ------
 (4, 3) 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


More **numpy broadcasting examples**

In [21]:
import numpy as np

x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

#x (4)
#y (5)
# trailing dimensions do not match
print (x.shape)
print (y.shape)
#print (x + y) #ValueError: operands could not be broadcast together with shapes (4,) (5,)
print()

#xx (4, 1)
#y  (   5)
#---------
#   (4, 5)

print (xx.shape)
print (" ", y.shape)
print("------")
print ((xx + y).shape)
print (xx + y)
print()

#x (   4)
#z (3, 4)
#--------
#  (3, 4)

print (" ", x.shape)
print (z.shape)
print("------")
print ((x + z).shape)
print (x + z)

(4,)
(5,)

(4, 1)
  (5,)
------
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]

  (4,)
(3, 4)
------
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


**Applications of broadcasting**

In [129]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# you cannot do matrix multiplication b/w v and w directly
#print(v*w)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print (np.reshape(v, (3, 1)) * w, "\n")

# note you can directly use np.outer method
print (np.outer(v,  w))

[[ 4  5]
 [ 8 10]
 [12 15]] 

[[ 4  5]
 [ 8 10]
 [12 15]]


In [133]:
# Add a vector to each row of a matrix

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
x = np.array([[1,2,3], [4,5,6]])     # x has shape (2, 3) 
v = np.array([1,2,3])                # v has shape    (3)

# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

[[2 4 6]
 [5 7 9]]


In [23]:
# Add a vector to each column of a matrix

# x has shape (2, 3) and w has shape (2,).
x = np.array([[1,2,3], [4,5,6]])   # x has shape (2, 3) 
w = np.array([4,5])                # w has shape (   2)

# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print(x.T,"\n\n", w, "\n")
print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same output.
w = np.reshape(w, (2, 1))
print("\n", x,"\n\n", w, "\n")
print(x + w)

# alternatively using newaxis to make w shape (2,1)
w = np.array([4,5])                # w has shape (   2)
w = w[:, np.newaxis]
print("\n", x,"\n\n", w, "\n")
print(x + w)

[[1 4]
 [2 5]
 [3 6]] 

 [4 5] 

[[ 5  6  7]
 [ 9 10 11]]

 [[1 2 3]
 [4 5 6]] 

 [[4]
 [5]] 

[[ 5  6  7]
 [ 9 10 11]]

 [[1 2 3]
 [4 5 6]] 

 [[4]
 [5]] 

[[ 5  6  7]
 [ 9 10 11]]


In [149]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]
