# Numpy: Part 3

In this notebook, you will learn:
 - Array mathematics
 - Statistics methods
 - Normalization
 - Vectorization
 
Read more: 
 - textbook (https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html) and
 - [Numpy website] (https://numpy.org/).

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [46]:
import numpy as np

### 1. Array mathematics

**Unary Universal Functions**

In [76]:
import numpy as np

# example of np.exp
x = np.array(1)
print('X dim: ', x.ndim, '\n\n', np.exp(x)) # result is (exp(1))

X dim:  0 

 2.718281828459045


If $ x = (x_1, x_2, ..., x_n)$ is a row vector then $np.exp(x)$ will apply the exponential function to every element of x. The output will thus be: $np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})$

In [77]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print('X dim: ', x.ndim, '\n\n', np.exp(x)) # result is (exp(1), exp(2), exp(3))

X dim:  1 

 [ 2.71828183  7.3890561  20.08553692]


In [80]:
# example of np.exp
x = np.array([[1, 2, 3],[4, 5, 6]])
print('X dim: ', x.ndim, '\n\n', np.exp(x)) # result is ([exp(1), exp(2), exp(3)][exp(4), exp(5), exp(6)])

X dim:  2 

 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


Furthermore, if x is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [81]:
print (x + 3)
print (1/x)

[[4 5 6]
 [7 8 9]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [49]:
a = np.array([1.1, 4.5, 9.9], float)

print(np.square(a))# [ 1.21 20.25 98.01]
print(np.sqrt(a))  # [1.04880885 2.12132034 3.14642654]
print(np.sign(a))  # [1. 1. 1.]

print(np.exp(a)) 
print(np.log(a))   # [0.09531018 1.5040774  2.29253476]
print(np.log2(a))  # [0.13750352 2.169925   3.30742853]
print(np.log10(a)) # [0.04139269 0.65321251 0.99563519]

print(np.floor(a)) # array([ 1., 4., 9.]) 
print(np.ceil(a))  # array([ 2., 5., 10.]) 
print(np.rint(a))   # array([ 1., 2., 2.])

[ 1.21 20.25 98.01]
[1.04880885 2.12132034 3.14642654]
[1. 1. 1.]
[3.00416602e+00 9.00171313e+01 1.99303704e+04]
[0.09531018 1.5040774  2.29253476]
[0.13750352 2.169925   3.30742853]
[0.04139269 0.65321251 0.99563519]
[1. 4. 9.]
[ 2.  5. 10.]
[ 1.  4. 10.]


**Binary Universal Functions**

In [50]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [51]:
# Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [52]:
# Elementwise product; both produce the array
print (x * y)
print (np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [53]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [54]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


**Note**: 
 - `*` is **elementwise multiplication**, not matrix multiplication. 
 - Use the **dot** function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

**Matrix Multiplication**

In [83]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print (v.dot(w))       # 9*11+10*12
print (np.dot(v, w))

219
219


In [86]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print ('Shapes: ', x.shape, v.shape, "=>", x.dot(v))
print ('Shapes: ', x.shape, v.shape, "=>", np.dot(x, v))

Shapes:  (2, 2) (2,) => [29 67]
Shapes:  (2, 2) (2,) => [29 67]


In [89]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print ('Shapes: ', x.shape, y.shape, "=>\n", x.dot(y))
print ('Shapes: ', x.shape, y.shape, "=>\n", np.dot(x, y))

Shapes:  (2, 2) (2, 2) =>
 [[19 22]
 [43 50]]
Shapes:  (2, 2) (2, 2) =>
 [[19 22]
 [43 50]]


In [58]:
# inner, outer, and cross products of matrices and vectors. 
# For vectors, the inner product is equivalent to the dot product
a = np.array([1, 4, 0], float) 
b = np.array([2, 2, 1], float)

print(np.outer(a, b))
print(np.inner(a, b))
print(np.cross(a, b))

[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
10.0
[ 4. -1. -6.]


Other matrix operations:
 - Transpose
 - Reshape

In [59]:
v = np.array([[1,2,3]])
print (v, v.shape, "\n") 
print (v.T, v.T.shape, "\n")

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
print (x, x.shape, "\n")
print (x.T, x.T.shape)

[[1 2 3]] (1, 3) 

[[1]
 [2]
 [3]] (3, 1) 

[[1 2 3 4]
 [5 6 7 8]] (2, 4) 

[[1 5]
 [2 6]
 [3 7]
 [4 8]] (4, 2)


In [60]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

print (x, x.shape, "\n")

# rank2 (4,2)
print (np.reshape(x, (4,2)), np.reshape(x, (4,2)).shape, "\n")
print (np.reshape(x, (4,-1)), np.reshape(x, (4,-1)).shape, "\n") # the unspecified value is inferred to be 2

# rank2 (1,8) and rank1 (8,)
print (np.reshape(x, (1,8)), np.reshape(x, (1,8)).shape, "\n")
print (x.flatten(), x.flatten().shape, "\n")

[[1 2 3 4]
 [5 6 7 8]] (2, 4) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2) 

[[1 2 3 4 5 6 7 8]] (1, 8) 

[1 2 3 4 5 6 7 8] (8,) 



### 2. Statistical methods

In [92]:
x = np.array([(14, 29, 34), (42, 5, 46), (1, 38, 44), (5, 16, 52)])

print(x)
print (np.sum(x))           # Compute sum of all elements; 
print (np.sum(x, axis=0))   # Compute sum of each column (along with row axis);
print (np.sum(x, axis=1))   # Compute sum of each row (along with column axis);

[[14 29 34]
 [42  5 46]
 [ 1 38 44]
 [ 5 16 52]]
326
[ 62  88 176]
[77 93 83 73]


In [91]:
print(x)
print(np.max(x))            # max of all elements
print(np.max(x, axis = 0))  # max for each column
print(np.max(x, axis = 1))  # max for each row

[[14 29 34]
 [42  5 46]
 [ 1 38 44]
 [ 5 16 52]]
52
[42 38 52]
[34 46 44 52]


**numpy.argmax()** function returns indices of the max element of the array in a particular axis. 

In [95]:
print(x)
print(np.argmax(x))           # index correponding to max of all elements (flattened) 
print(np.argmax(x, axis = 0)) # index correponding to max for each column (along with row axis)
print(np.argmax(x, axis = 1)) # index correponding to max for each row  (along with column axis)

[[14 29 34]
 [42  5 46]
 [ 1 38 44]
 [ 5 16 52]]
11
[1 2 3]
[2 2 2 2]


### 3. Column normalization

For column normalizatio, the volues for each column will be normalized so the each column's unit lenght is 1.

For example, $$x = 
\begin{bmatrix}
    0 &  0  & 30 & 400\\
    3 & 30  & 40 &   0\\
    4 & 40  &  0 & 300\\
\end{bmatrix}\tag{1}$$ 

then we need compute norm for each column so we need to do norm along **row axis, axis = 0, not axis = 1**

$$\| x\| = np.linalg.norm(x, axis = 0, keepdims = True) = \begin{bmatrix}
    5 & 50 & 50 & 500\\
\end{bmatrix}\tag{2} $$

and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0. & 0. & 0.6 &0.8\\
   0.6 &0.6 &0.8  &0. \\
   0.8 &0.8 &0.   &0.6\\
\end{bmatrix}\tag{3}$$ 

Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn.

In [106]:
import numpy as np
x = np.array([[0,  0, 30, 400],
              [3, 30, 40,   0],
              [4, 40,  0, 300]])

# Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
x_norm = np.linalg.norm(x, ord = 2, axis = 0, keepdims = True)
print (x_norm, x_norm.shape,'\n')
    
# Divide x by its norm.
x = x / x_norm

print(x)      

[[  5.  50.  50. 500.]] (1, 4) 

[[0.  0.  0.6 0.8]
 [0.6 0.6 0.8 0. ]
 [0.8 0.8 0.  0.6]]


### 4. Vectorization

You deal with very large datasets very frequently. Hence, a non-computationally-optimal function can become a huge bottleneck in your algorithm and can result in a model that takes ages to run. To make sure that your code is  computationally efficient, you will use vectorization. For example, try to tell the difference between the following implementations of the dot/elementwise product.

In [123]:
import time

x1 = range(1000000)
x2 = range(1000000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication time = " + str(1000*(toc - tic)) + "ms")

dot time = 437.5ms
elementwise multiplication time = 531.25ms


In [124]:
x1 = np.arange(1000000)
x2 = np.arange(1000000)
### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot  time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication time = " + str(1000*(toc - tic)) + "ms")


dot  time = 0.0ms
elementwise multiplication time = 0.0ms


As you may have noticed, the vectorized implementation is much cleaner and more efficient. 

**Note** that `np.dot()` performs a matrix-matrix or matrix-vector multiplication. This is different from `np.multiply()` and the `*` operator, which performs an element-wise multiplication.

In [ ]:
<img src="images/image2vector_kiank.png" style="width:500px;height:300;">